### ISSUE TITLE
Fullt Kiosk Browser fails randomly

### ISSUE THREAD

**Issue by angr72** [hasl-sensor/lovelace-hasl-departure-card#31]
Having a dashboard published to both a Fire Hd and a Samsung Android tab. Both are running the Fully Kiosk Browser.
9 out of 10 the departure card shows like in the screenshoot (pardon the mirror reflection). So it works sometimes

Going to a computer and test the same dashboard it looks fine

![64B2626B-2181-4CA1-93BF-F8A9EAD1EEB2](https://user-images.githubusercontent.com/122445919/232198858-f096d71f-6b51-449e-912a-9cc2c17f4041.jpeg)

**Comment by DSorlov** [comment]
Do you have any update on this? Sometimes android have some issues with caching of resources and perhaps this could be the same?

**Comment by angr72** [comment]
I have teo devices one Samsung and on Amazon Fire HD.
Tested today on computer and the devices. Still the same unfortunately. Both devices updated.
Maybe there is something like you said about caching coz randomly it works.

<img width="800" alt="image" src="https://github.com/hasl-sensor/lovelace-hasl-departure-card/assets/122445919/ac3f7327-1c9f-475b-906a-eb8de7fce839">

**Comment by DSorlov** [comment]
After much research into this it seems like many custom integrations have theese issues. It can depend on load order and if you are lucky. I will welcome anyone who wants to look into it but it is not a problem with the card or integration so I will not for now due to time constraints. 

See https://github.com/custom-cards/button-card/issues/689 for example as another card failing in the same way. There is a workaround that most probably also will work for this.
