### ISSUE TITLE
My iOS app shows later departure than Web Page

### ISSUE THREAD

**Issue by TheGreatBorg** [hasl-sensor/lovelace-hasl-departure-card#4]
I'm not sure if this is Card-related - but it is quite odd.

I have just observed that the scheduler times in Companion app shows departure times an hour away compared to the same view from a browser. Why? and it is then not useful for anything. I took the screenshots below at 16:38.

Here is the view from Web Browser.
![image](https://user-images.githubusercontent.com/31419036/73848486-837b2980-4828-11ea-978d-d2a45fb6fe0c.png)

And here is the same view from the app taken at exact same time (16:38):

![image](https://user-images.githubusercontent.com/31419036/73848681-dd7bef00-4828-11ea-8417-713738c80262.png)

**Comment by dimmanramone** [comment]
@TheGreatBorg This has been reported before and unfortunatelly I couldn't reproduce. [#26](https://github.com/DSorlov/hasl-platform/issues/26) Seems to be iOS specific. I'll try to get my hands on a  iPhone and try to investigate. Do you have the same problem on Safari or Chrome on iOS too? or is it just the companion app?

**Comment by TheGreatBorg** [comment]
Safari did the same but I just tried out Chrome now when you mentioned that and yes - that's exactly the same. But it is rather strange like the iPhone is using another time zone or HA is using GMT and that's what confuses iPhone.

But this part in the top is actually OK:

![image](https://user-images.githubusercontent.com/31419036/74685827-fba20180-51cf-11ea-8e31-f65691a7532a.png)

**Comment by henrikbla** [comment]
Hi,

Thanks for the great work on the plugin.

Unfortunately, I can confirm that this bug still seems to exist. Please see attached a screenshot of the same view as viewed through Android and through iOS (13.4.1) native app. Android shows the departure times correctly, while for iOS the times are two hours off. I would guess the reason why they are two hours off now instead of one is because of Summer time (in comparison to February).

Let me know if there is anything I can do to help, happy to install a debug / beta version if needed.

![IMG-20200528-WA0000](https://user-images.githubusercontent.com/9527638/83123889-c01fa900-a0d5-11ea-81a5-4ed91d26a213.jpg)

![Screenshot_20200528-112004](https://user-images.githubusercontent.com/9527638/83124052-f9581900-a0d5-11ea-9bdd-b083c0da184d.jpg)
